### ISSUE TITLE
obj 문제

### ISSUE THREAD

**Issue by novaprospectCAU** [KLP-Capstone/Sass#15]
일단 optimization 브랜치에서 obj가 메서드 하나도 호출 못하던건 #include ast.hpp 해서 메서드를 사용할 수 있게 했습니다. 다만, 주요 로직은 아직 안 채워서 앞으로 해야 합니다.

**Comment by zzeo14** [comment]
수고 많으십니다.

**Comment by ArcRoot** [comment]
good
